apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cookie-webpage
  name: jendarey-cookie-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cookie-webpage
  type: LoadBalancer
status:
  loadBalancer: {}

