apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cookie-webpage
  name: cookie-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cookie-webpage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cookie-webpage
    spec:
      containers:
      - image: jendaredocker/jendarey-cookie-company-webpage-main:v1
        name: jendarey-cookie-company-webpage-main
        ports:
        - containerPort: 8080
        resources: {}
status: {}

